// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class Address
{
    [Key]
    public int address_id { get; set; }

    public int ClientID { get; set; }

    [Required]
    [StringLength(500)]
    public string full_description { get; set; }

    [Required]
    [StringLength(200)]
    public string city { get; set; }

    [StringLength(50)]
    public string postal_code { get; set; }

    [Required]
    [StringLength(100)]
    public string country { get; set; }

    public bool? is_default { get; set; }

    public DateTime? created_at { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Addresses")]
    public virtual Client Client { get; set; }
}