// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class CartItem
{
    public int CartId { get; set; }

    public int VariantId { get; set; }

    public int Quantity { get; set; }

    [Key]
    public int CartItemId { get; set; }

    [ForeignKey("CartId")]
    [InverseProperty("CartItems")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("VariantId")]
    [InverseProperty("CartItems")]
    public virtual ProductVariant Variant { get; set; }
}