// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class Cart
{
    [Key]
    public int cart_id { get; set; }

    public int? user_id { get; set; }

    [StringLength(200)]
    public string session_id { get; set; }

    public DateTime? expires_at { get; set; }

    public DateTime created_at { get; set; }

    [InverseProperty("cart")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [ForeignKey("user_id")]
    [InverseProperty("Carts")]
    public virtual User user { get; set; }
}