// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("name", Name = "IX_Categories_Name")]
public partial class Category
{
    [Key]
    public int category_id { get; set; }

    public int? parent_category_id { get; set; }

    [Required]
    [StringLength(200)]
    public string name { get; set; }

    [StringLength(1000)]
    public string description { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    [InverseProperty("category")]
    public virtual ICollection<CommissionRule> CommissionRules { get; set; } = new List<CommissionRule>();

    [InverseProperty("parent_category")]
    public virtual ICollection<Category> Inverseparent_category { get; set; } = new List<Category>();

    [InverseProperty("category")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [ForeignKey("parent_category_id")]
    [InverseProperty("Inverseparent_category")]
    public virtual Category parent_category { get; set; }
}