// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("ColorName", Name = "UQ_Colors_ColorName", IsUnique = true)]
public partial class Color
{
    [Key]
    public int ColorID { get; set; }

    [Required]
    [StringLength(50)]
    public string ColorName { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string HexCode { get; set; }

    public int DisplayOrder { get; set; }

    [InverseProperty("Color")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}