// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("MaterialName", Name = "UQ_Materials_MaterialName", IsUnique = true)]
public partial class Material
{
    [Key]
    public int MaterialID { get; set; }

    [Required]
    [StringLength(100)]
    public string MaterialName { get; set; }

    public int DisplayOrder { get; set; }

    [InverseProperty("Material")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}