// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("OrderID", Name = "IX_OrderDetails_OrderID")]
public partial class OrderDetail
{
    [Key]
    public int OrderDetailsID { get; set; }

    public int OrderID { get; set; }

    public int VariantID { get; set; }

    public int Quantity { get; set; }

    [StringLength(60)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? UnitPrice { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("VariantID")]
    [InverseProperty("OrderDetails")]
    public virtual ProductVariant Variant { get; set; }
}