// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class Order
{
    [Key]
    public int OrderID { get; set; }

    public DateTime? OrderDate { get; set; }

    public int ClientID { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal TotalOrder { get; set; }

    [StringLength(60)]
    public string Status { get; set; }

    public int address_id { get; set; }

    public int? PaymentMethodID { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Orders")]
    public virtual Client Client { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("PaymentMethodID")]
    [InverseProperty("Orders")]
    public virtual PaymentMethod PaymentMethod { get; set; }
}