// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("order_id", Name = "IX_Payments_Order")]
public partial class Payment
{
    [Key]
    public int payment_id { get; set; }

    public int order_id { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal amount { get; set; }

    [Required]
    [StringLength(8)]
    public string currency { get; set; }

    [Required]
    [StringLength(32)]
    public string status { get; set; }

    [StringLength(255)]
    public string provider_txn_id { get; set; }

    public string provider_response { get; set; }

    public DateTime created_at { get; set; }

    [InverseProperty("payment")]
    public virtual ICollection<Refund> Refunds { get; set; } = new List<Refund>();

    [ForeignKey("order_id")]
    [InverseProperty("Payments")]
    public virtual Order order { get; set; }
}