// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class PaymentMethod
{
    [Key]
    public int PaymentMethodID { get; set; }

    public int ClientID { get; set; }

    [Required]
    [StringLength(255)]
    public string PaymentType { get; set; }

    [Required]
    [StringLength(4)]
    public string LastFourDigits { get; set; }

    [Required]
    [StringLength(255)]
    public string CardBrand { get; set; }

    public int? ExpiryMonth { get; set; }

    public int? ExpiryYear { get; set; }

    [Required]
    [StringLength(200)]
    public string CardholderName { get; set; }

    [Required]
    [StringLength(255)]
    public string PaymentToken { get; set; }

    public bool IsDefault { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? LastUsedDate { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("PaymentMethods")]
    public virtual Client Client { get; set; }

    [InverseProperty("PaymentMethod")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}