// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("vendor_id", Name = "IX_PayoutRequests_Vendor")]
public partial class PayoutRequest
{
    [Key]
    public int payout_id { get; set; }

    public int vendor_id { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal amount { get; set; }

    [Required]
    [StringLength(32)]
    public string status { get; set; }

    public DateTime requested_at { get; set; }

    public DateTime? paid_at { get; set; }

    [StringLength(100)]
    public string method { get; set; }

    [StringLength(255)]
    public string reference { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("PayoutRequests")]
    public virtual Vendor vendor { get; set; }
}