// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class ProductImage
{
    [Key]
    public int ImageID { get; set; }

    public int ProductID { get; set; }

    [Required]
    [StringLength(500)]
    public string ImageURL { get; set; }

    [StringLength(255)]
    public string AltText { get; set; }

    public bool? IsPrimary { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductImages")]
    public virtual Product Product { get; set; }
}