// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("name", Name = "IX_Products_Name")]
[Index("vendor_id", Name = "IX_Products_Vendor")]
public partial class Product
{
    [Key]
    public int product_id { get; set; }

    public int vendor_id { get; set; }

    public int? category_id { get; set; }

    [Required]
    [StringLength(300)]
    public string name { get; set; }

    public string description { get; set; }

    public bool is_deleted { get; set; }

    public DateTime created_at { get; set; }

    public DateTime? updated_at { get; set; }

    [InverseProperty("product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("product")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [InverseProperty("product")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    [InverseProperty("product")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [ForeignKey("category_id")]
    [InverseProperty("Products")]
    public virtual Category category { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("Products")]
    public virtual Vendor vendor { get; set; }
}