// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("ProductID", Name = "IX_ProductVariants_ProductID")]
public partial class ProductVariant
{
    [Key]
    public int VariantID { get; set; }

    public int ProductID { get; set; }

    [Required]
    [StringLength(100)]
    public string VariantName { get; set; }

    [Required]
    [StringLength(100)]
    public string VariantValue { get; set; }

    public int StockQuantity { get; set; }

    public bool? IsActive { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductVariants")]
    public virtual Product Product { get; set; }
}