// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("product_id", "display_order", Name = "IX_ProductImages_Product_DisplayOrder")]
public partial class ProductImage
{
    [Key]
    public int image_id { get; set; }

    public int product_id { get; set; }

    public int? variant_id { get; set; }

    [Required]
    [StringLength(2000)]
    public string image_url { get; set; }

    [StringLength(512)]
    public string alt_text { get; set; }

    public int display_order { get; set; }

    public bool is_primary { get; set; }

    [ForeignKey("product_id")]
    [InverseProperty("ProductImages")]
    public virtual Product product { get; set; }

    [ForeignKey("variant_id")]
    [InverseProperty("ProductImages")]
    public virtual ProductVariant variant { get; set; }
}