// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("CategoryID", Name = "IX_Products_CategoryID")]
public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [Required]
    [StringLength(255)]
    public string ProductName { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal BasePrice { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public int CategoryID { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    [InverseProperty("Product")]
    public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; } = new List<SupplyOrderDetail>();
}