// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class Refund
{
    [Key]
    public int refund_id { get; set; }

    public int? payment_id { get; set; }

    public int? order_id { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal amount { get; set; }

    [Required]
    [StringLength(32)]
    public string status { get; set; }

    [StringLength(1000)]
    public string reason { get; set; }

    public DateTime created_at { get; set; }

    [ForeignKey("order_id")]
    [InverseProperty("Refunds")]
    public virtual Order order { get; set; }

    [ForeignKey("payment_id")]
    [InverseProperty("Refunds")]
    public virtual Payment payment { get; set; }
}