// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("SizeName", Name = "UQ_Sizes_SizeName", IsUnique = true)]
public partial class Size
{
    [Key]
    public int SizeID { get; set; }

    [Required]
    [StringLength(50)]
    public string SizeName { get; set; }

    public int DisplayOrder { get; set; }

    [InverseProperty("Size")]
    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}