// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class SupplyOrderDetail
{
    [Key]
    public int SupplyOrderDetailID { get; set; }

    public int SupplyOrderID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("SupplyOrderDetails")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplyOrderID")]
    [InverseProperty("SupplyOrderDetails")]
    public virtual SupplyOrder SupplyOrder { get; set; }
}