// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class SupplyOrder
{
    [Key]
    public int SupplyOrderID { get; set; }

    public DateTime SupplyDate { get; set; }

    public int VendorID { get; set; }

    public int EmployeeID { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Total { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("SupplyOrders")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("SupplyOrder")]
    public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; } = new List<SupplyOrderDetail>();

    [ForeignKey("VendorID")]
    [InverseProperty("SupplyOrders")]
    public virtual Vendor Vendor { get; set; }
}