// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("vendor_id", "created_at", Name = "IX_VendorTransactions_Vendor_Created")]
public partial class VendorTransaction
{
    [Key]
    public int txn_id { get; set; }

    public int vendor_id { get; set; }

    [Required]
    [StringLength(32)]
    public string txn_type { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal amount { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? balance_after { get; set; }

    public int? order_id { get; set; }

    [StringLength(1000)]
    public string note { get; set; }

    public DateTime created_at { get; set; }

    [ForeignKey("order_id")]
    [InverseProperty("VendorTransactions")]
    public virtual Order order { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("VendorTransactions")]
    public virtual Vendor vendor { get; set; }
}