// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class VendorUser
{
    [Key]
    public int id { get; set; }

    public int vendor_id { get; set; }

    public int user_id { get; set; }

    [Required]
    [StringLength(32)]
    public string vendor_role { get; set; }

    public DateTime added_at { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("VendorUsers")]
    public virtual User user { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("VendorUsers")]
    public virtual Vendor vendor { get; set; }
}