// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class Vendor
{
    [Key]
    public int vendor_id { get; set; }

    public int? owner_user_id { get; set; }

    [Required]
    [StringLength(255)]
    public string business_name { get; set; }

    [StringLength(128)]
    public string tax_id { get; set; }

    [StringLength(50)]
    public string phone { get; set; }

    [Required]
    [StringLength(32)]
    public string status { get; set; }

    public int? approved_by { get; set; }

    public DateTime? approved_at { get; set; }

    public DateTime created_at { get; set; }

    [InverseProperty("vendor")]
    public virtual ICollection<CommissionRule> CommissionRules { get; set; } = new List<CommissionRule>();

    [InverseProperty("vendor")]
    public virtual ICollection<File> Files { get; set; } = new List<File>();

    [InverseProperty("vendor")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("vendor")]
    public virtual ICollection<PayoutRequest> PayoutRequests { get; set; } = new List<PayoutRequest>();

    [InverseProperty("vendor")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("vendor")]
    public virtual ICollection<VendorTransaction> VendorTransactions { get; set; } = new List<VendorTransaction>();

    [InverseProperty("vendor")]
    public virtual ICollection<VendorUser> VendorUsers { get; set; } = new List<VendorUser>();

    [ForeignKey("owner_user_id")]
    [InverseProperty("Vendors")]
    public virtual User owner_user { get; set; }
}