// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CommissionRecord> CommissionRecords { get; set; }

    public virtual DbSet<CommissionRule> CommissionRules { get; set; }

    public virtual DbSet<File> Files { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PayoutRequest> PayoutRequests { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<Refund> Refunds { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vendor> Vendors { get; set; }

    public virtual DbSet<VendorTransaction> VendorTransactions { get; set; }

    public virtual DbSet<VendorUser> VendorUsers { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.address_id).HasName("PK__Addresse__CAA247C893BFC147");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.user).WithMany(p => p.Addresses)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Addresses_User");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.cart_id).HasName("PK__Carts__2EF52A27AD89EE38");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.user).WithMany(p => p.Carts)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Carts_User");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.cart_item_id).HasName("PK__CartItem__5D9A6C6EEF585EF5");

            entity.Property(e => e.added_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.quantity).HasDefaultValue(1);

            entity.HasOne(d => d.cart).WithMany(p => p.CartItems).HasConstraintName("FK_CartItems_Cart");

            entity.HasOne(d => d.variant).WithMany(p => p.CartItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartItems_Variant");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.category_id).HasName("PK__Categori__D54EE9B4089CC76C");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.is_active).HasDefaultValue(true);

            entity.HasOne(d => d.parent_category).WithMany(p => p.Inverseparent_category).HasConstraintName("FK_Categories_Parent");
        });

        modelBuilder.Entity<CommissionRecord>(entity =>
        {
            entity.HasKey(e => e.rec_id).HasName("PK__Commissi__97D3CABD5997F3AF");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.order_item).WithMany(p => p.CommissionRecords).HasConstraintName("FK_CommissionRecords_OrderItem");
        });

        modelBuilder.Entity<CommissionRule>(entity =>
        {
            entity.HasKey(e => e.rule_id).HasName("PK__Commissi__E92A92967A9EEE20");

            entity.Property(e => e.commission_percent).HasDefaultValue(10.00m);
            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.scope).HasDefaultValue("global");

            entity.HasOne(d => d.category).WithMany(p => p.CommissionRules).HasConstraintName("FK_CommissionRules_Category");

            entity.HasOne(d => d.vendor).WithMany(p => p.CommissionRules).HasConstraintName("FK_CommissionRules_Vendor");
        });

        modelBuilder.Entity<File>(entity =>
        {
            entity.HasKey(e => e.file_id).HasName("PK__Files__07D884C6D9FF680C");

            entity.Property(e => e.uploaded_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.uploaded_byNavigation).WithMany(p => p.Files)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Files_User");

            entity.HasOne(d => d.vendor).WithMany(p => p.Files)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Files_Vendor");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.order_id).HasName("PK__Orders__46596229E44BE77B");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.currency).HasDefaultValue("USD");
            entity.Property(e => e.status).HasDefaultValue("pending_payment");

            entity.HasOne(d => d.billing_address).WithMany(p => p.Orderbilling_addresses).HasConstraintName("FK_Orders_BillingAddress");

            entity.HasOne(d => d.shipping_address).WithMany(p => p.Ordershipping_addresses).HasConstraintName("FK_Orders_ShippingAddress");

            entity.HasOne(d => d.user).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_User");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.order_item_id).HasName("PK__OrderIte__3764B6BCBE7BE59A");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.quantity).HasDefaultValue(1);

            entity.HasOne(d => d.order).WithMany(p => p.OrderItems).HasConstraintName("FK_OrderItems_Order");

            entity.HasOne(d => d.product).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Product");

            entity.HasOne(d => d.variant).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_OrderItems_Variant");

            entity.HasOne(d => d.vendor).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Vendor");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.payment_id).HasName("PK__Payments__ED1FC9EAF80145A3");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.currency).HasDefaultValue("USD");
            entity.Property(e => e.status).HasDefaultValue("pending");

            entity.HasOne(d => d.order).WithMany(p => p.Payments).HasConstraintName("FK_Payments_Order");
        });

        modelBuilder.Entity<PayoutRequest>(entity =>
        {
            entity.HasKey(e => e.payout_id).HasName("PK__PayoutRe__3B0771ECE4C6ED6E");

            entity.Property(e => e.requested_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.status).HasDefaultValue("pending");

            entity.HasOne(d => d.vendor).WithMany(p => p.PayoutRequests).HasConstraintName("FK_PayoutRequests_Vendor");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.product_id).HasName("PK__Products__47027DF551B9DF77");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.category).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Products_Category");

            entity.HasOne(d => d.vendor).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Vendor");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.image_id).HasName("PK__ProductI__DC9AC955EF088312");

            entity.HasOne(d => d.product).WithMany(p => p.ProductImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductImages_Product");

            entity.HasOne(d => d.variant).WithMany(p => p.ProductImages)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_ProductImages_Variant");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.variant_id).HasName("PK__ProductV__EACC68B75C9B94F6");

            entity.HasIndex(e => e.sku, "UQ_ProductVariants_SKU")
                .IsUnique()
                .HasFilter("([sku] IS NOT NULL)");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.is_active).HasDefaultValue(true);

            entity.HasOne(d => d.product).WithMany(p => p.ProductVariants)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductVariants_Product");
        });

        modelBuilder.Entity<Refund>(entity =>
        {
            entity.HasKey(e => e.refund_id).HasName("PK__Refunds__897E9EA33E88EDE8");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.status).HasDefaultValue("pending");

            entity.HasOne(d => d.order).WithMany(p => p.Refunds).HasConstraintName("FK_Refunds_Order");

            entity.HasOne(d => d.payment).WithMany(p => p.Refunds)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Refunds_Payment");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.review_id).HasName("PK__Reviews__60883D903050FB56");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.product).WithMany(p => p.Reviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Product");

            entity.HasOne(d => d.user).WithMany(p => p.Reviews).HasConstraintName("FK_Reviews_User");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("PK__Users__B9BE370FDBC391D2");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.role).HasDefaultValue("customer");
        });

        modelBuilder.Entity<Vendor>(entity =>
        {
            entity.HasKey(e => e.vendor_id).HasName("PK__Vendors__0F7D2B78F79BD29B");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.status).HasDefaultValue("pending");

            entity.HasOne(d => d.owner_user).WithMany(p => p.Vendors)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Vendors_OwnerUser");
        });

        modelBuilder.Entity<VendorTransaction>(entity =>
        {
            entity.HasKey(e => e.txn_id).HasName("PK__VendorTr__37F08046BCE0F88F");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.order).WithMany(p => p.VendorTransactions)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_VendorTransactions_Order");

            entity.HasOne(d => d.vendor).WithMany(p => p.VendorTransactions).HasConstraintName("FK_VendorTransactions_Vendor");
        });

        modelBuilder.Entity<VendorUser>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__VendorUs__3213E83F734B1100");

            entity.Property(e => e.added_at).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.vendor_role).HasDefaultValue("vendor_staff");

            entity.HasOne(d => d.user).WithMany(p => p.VendorUsers).HasConstraintName("FK_VendorUsers_User");

            entity.HasOne(d => d.vendor).WithMany(p => p.VendorUsers).HasConstraintName("FK_VendorUsers_Vendor");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}