// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("cart_id", Name = "IX_CartItems_Cart")]
public partial class CartItem
{
    [Key]
    public int cart_item_id { get; set; }

    public int cart_id { get; set; }

    public int variant_id { get; set; }

    public int quantity { get; set; }

    public DateTime added_at { get; set; }

    [ForeignKey("cart_id")]
    [InverseProperty("CartItems")]
    public virtual Cart cart { get; set; }

    [ForeignKey("variant_id")]
    [InverseProperty("CartItems")]
    public virtual ProductVariant variant { get; set; }
}