// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("order_item_id", Name = "IX_CommissionRecords_OrderItem")]
public partial class CommissionRecord
{
    [Key]
    public int rec_id { get; set; }

    public int order_item_id { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal commission_amount { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal commission_percent { get; set; }

    public DateTime created_at { get; set; }

    [ForeignKey("order_item_id")]
    [InverseProperty("CommissionRecords")]
    public virtual OrderItem order_item { get; set; }
}