// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class CommissionRule
{
    [Key]
    public int rule_id { get; set; }

    [Required]
    [StringLength(32)]
    public string scope { get; set; }

    public int? vendor_id { get; set; }

    public int? category_id { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal commission_percent { get; set; }

    public DateTime created_at { get; set; }

    [ForeignKey("category_id")]
    [InverseProperty("CommissionRules")]
    public virtual Category category { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("CommissionRules")]
    public virtual Vendor vendor { get; set; }
}