// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

public partial class File
{
    [Key]
    public int file_id { get; set; }

    public int? uploaded_by { get; set; }

    public int? vendor_id { get; set; }

    [Required]
    [StringLength(2000)]
    public string file_url { get; set; }

    [StringLength(128)]
    public string file_type { get; set; }

    public DateTime uploaded_at { get; set; }

    [ForeignKey("uploaded_by")]
    [InverseProperty("Files")]
    public virtual User uploaded_byNavigation { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("Files")]
    public virtual Vendor vendor { get; set; }
}