// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("order_id", Name = "IX_OrderItems_Order")]
[Index("vendor_id", Name = "IX_OrderItems_Vendor")]
public partial class OrderItem
{
    [Key]
    public int order_item_id { get; set; }

    public int order_id { get; set; }

    public int product_id { get; set; }

    public int? variant_id { get; set; }

    public int vendor_id { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal unit_price { get; set; }

    public int quantity { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal line_total { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal commission_amount { get; set; }

    public DateTime created_at { get; set; }

    [InverseProperty("order_item")]
    public virtual ICollection<CommissionRecord> CommissionRecords { get; set; } = new List<CommissionRecord>();

    [ForeignKey("order_id")]
    [InverseProperty("OrderItems")]
    public virtual Order order { get; set; }

    [ForeignKey("product_id")]
    [InverseProperty("OrderItems")]
    public virtual Product product { get; set; }

    [ForeignKey("variant_id")]
    [InverseProperty("OrderItems")]
    public virtual ProductVariant variant { get; set; }

    [ForeignKey("vendor_id")]
    [InverseProperty("OrderItems")]
    public virtual Vendor vendor { get; set; }
}