// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("product_id", Name = "IX_ProductVariants_Product")]
public partial class ProductVariant
{
    [Key]
    public int variant_id { get; set; }

    public int product_id { get; set; }

    [StringLength(100)]
    public string sku { get; set; }

    [StringLength(200)]
    public string variant_name { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal price { get; set; }

    public int stock_quantity { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime? updated_at { get; set; }

    [InverseProperty("variant")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [InverseProperty("variant")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("variant")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [ForeignKey("product_id")]
    [InverseProperty("ProductVariants")]
    public virtual Product product { get; set; }
}