// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("product_id", Name = "IX_Reviews_Product")]
public partial class Review
{
    [Key]
    public int review_id { get; set; }

    public int product_id { get; set; }

    public int user_id { get; set; }

    public byte rating { get; set; }

    [StringLength(2000)]
    public string comment { get; set; }

    public DateTime created_at { get; set; }

    [ForeignKey("product_id")]
    [InverseProperty("Reviews")]
    public virtual Product product { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("Reviews")]
    public virtual User user { get; set; }
}