// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendora.Models;

[Index("email", Name = "UQ__Users__AB6E6164DA926B30", IsUnique = true)]
public partial class User
{
    [Key]
    public int user_id { get; set; }

    [Required]
    [StringLength(255)]
    public string email { get; set; }

    [StringLength(512)]
    public string password_hash { get; set; }

    [Required]
    [StringLength(32)]
    public string role { get; set; }

    [StringLength(100)]
    public string first_name { get; set; }

    [StringLength(100)]
    public string last_name { get; set; }

    public bool is_active { get; set; }

    public bool email_verified { get; set; }

    public DateTime created_at { get; set; }

    public DateTime? last_login_at { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    [InverseProperty("user")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("uploaded_byNavigation")]
    public virtual ICollection<File> Files { get; set; } = new List<File>();

    [InverseProperty("user")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("user")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [InverseProperty("user")]
    public virtual ICollection<VendorUser> VendorUsers { get; set; } = new List<VendorUser>();

    [InverseProperty("owner_user")]
    public virtual ICollection<Vendor> Vendors { get; set; } = new List<Vendor>();
}